# Generated by Django 3.2 on 2021-04-29 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('born', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'babies',
            },
        ),
        migrations.CreateModel(
            name='Nap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.baby')),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=255)),
                ('foodType', models.CharField(max_length=255)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.baby')),
            ],
        ),
        migrations.CreateModel(
            name='Diaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poop', models.BooleanField()),
                ('wet', models.BooleanField()),
                ('time', models.DateTimeField()),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.baby')),
            ],
        ),
    ]
