# Generated by Django 3.2 on 2021-05-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_guardian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='foodType',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='unit',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
