# Generated by Django 3.2 on 2021-05-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210505_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nap',
            name='endTime',
            field=models.DateTimeField(null=True),
        ),
    ]
