# Generated by Django 3.2 on 2021-05-06 07:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_auto_20210506_0754'),
    ]

    operations = [
        migrations.RunSQL('UPDATE api_guardian SET owner_id = user_id;'),
        migrations.RunSQL('UPDATE api_guardian SET status = \'ACTIVE\';'),
    ]
