version: 2
jobs:
  build:
    working_directory: ~/project/frontend
    docker:
      - image: circleci/node:14-browsers
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install-dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
      - run:
          name: angular-build
          command: ng build --prod --no-progress
      - run:
          name: angular-test
          command: ng test --single-run --no-progress
      - run:
          name: angular-lint
          command: ng lint
      - run:
          name: Upload reports to Codecov
          command: bash <(curl -s https://codecov.io/bash) -Z
