version: 2.1
jobs:

  frontend:
    working_directory: ~/project/frontend
    docker:
      - image: circleci/node:14-browsers
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
            key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install-dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
      - run:
          name: angular-lint
          command: yarn ng lint
      - run:
          name: angular-test
          command: yarn ng test --code-coverage --watch false --progress false
      - run:
          name: angular-build
          command: yarn ng build --prod --no-progress
      - run:
          name: Upload reports to Codecov
          command: bash <(curl -s https://codecov.io/bash) -Z


  backend:
    working_directory: ~/project/backend
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          key: pipenv-dependency-cache-{{ checksum "Pipfile.lock" }}
      - run:
          name: install-dependencies
          command: pipenv install
      - save_cache:
          key: pipenv-dependency-cache-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
      - run:
          name: create .env
          command: cp bobocare/.env.example bobocare/.env
      - run:
          name: pylint
          command: pipenv run pylint api
      - run:
          name: test
          command: pipenv run python manage.py test --noinput
      - run:
          name: Upload reports to Codecov
          command: bash <(curl -s https://codecov.io/bash) -Z

workflows:
  build_and_test:
    jobs:
      - frontend
      - backend
